# Generated by Django 2.2.3 on 2019-11-20 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pass_collector_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourse_name', models.CharField(max_length=200, verbose_name='sourse_name')),
                ('user_login', models.CharField(max_length=200, verbose_name='user_login')),
                ('user_password', models.CharField(max_length=200, verbose_name='user_passord')),
                ('password_creation_date', models.DateTimeField(null=True, verbose_name='password_creation_date')),
                ('link_to_site', models.CharField(max_length=200, verbose_name='link_to_site')),
                ('count_of_search', models.IntegerField(default=0, verbose_name='count_of_search')),
                ('count_of_copy', models.IntegerField(default=0, verbose_name='count_of_copy')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Password',
        ),
    ]
